export const CLEAR_THINKING_PREVIEW = {
  id: 'preview-clear-thinking',
  title: 'Clear Thinking',
  author: 'Shane Parrish',
  publishedYear: '2023',
  coverImage: 'https://covers.openlibrary.org/b/id/14467861-M.jpg',
  summary: 'A guide to making better decisions by upgrading your mental defaults and building the habits of mind that lead to exceptional outcomes.',
  addedAt: new Date().toISOString(),
  lastAccessedAt: new Date().toISOString(),
  lessonPlan: {
    id: 'preview-plan-1',
    bookId: 'preview-clear-thinking',
    generatedAt: new Date().toISOString(),
    modules: [
      {
        id: 'mod-1', number: 1, status: 'applied',
        title: 'The Enemy of Clear Thinking',
        keyWisdom: 'Your defaults run the show unless you intervene.',
        quickSummary: 'Most of our decisions are made on autopilot by biological and social defaults — not by our rational minds. These defaults evolved for survival, not for modern decision-making. The first step to thinking clearly is recognizing when your defaults are in the driver\'s seat.',
        focusedLearningBlock: 'Read pages 1–18 of the Introduction. As you read, underline every moment where Parrish describes a decision that went wrong because of a default. Hold in mind: what is the one default you notice most in yourself?',
        detailedBreakdown: '**What are defaults?**\nParrish identifies four core defaults — emotion, ego, social, and inertia — that govern most of our decisions. They are not bugs; they are evolutionary features that kept our ancestors alive.\n\n**Why they backfire**\nThese defaults trigger fast, automatic responses before our rational mind can engage. The emotion default makes us react before we think. The ego default makes us protect self-image over accuracy. The social default makes us conform to avoid exclusion. The inertia default makes us resist change even when change is clearly better.\n\n**The key misconception**\nMost people believe they are rational thinkers who occasionally let emotions slip in. Parrish argues the opposite: we are default-driven machines who occasionally interrupt those defaults with reason.\n\n**Apply This:** Think of a decision you made this week. Which default was most likely in control — emotion, ego, social pressure, or inertia?',
        dailyReflection: 'Without looking back, what was the core idea of this lesson?\n\nWhen in the last month did one of your defaults lead you to a decision you later regretted? What would it have taken to pause before acting?',
        diffuseThinkingPrompt: 'If your defaults were a character in a movie, what role would they play — the hero, the villain, or the sidekick?',
        deliberatePracticeTask: 'Track your defaults for one day. Each time you make a decision — from what to eat to how to respond to an email — pause and ask: "Is this me choosing, or a default running?" Note which default fired most often. You\'ll notice patterns by end of day.',
      },
      {
        id: 'mod-2', number: 2, status: 'practiced',
        title: 'Building the Strength to Pause',
        keyWisdom: 'Create space between stimulus and response — everything lives in that gap.',
        quickSummary: 'Knowing your defaults exist isn\'t enough. You need the strength to pause when they fire. Parrish introduces the concept of "the space" — the brief window between a trigger and your reaction where better choices are made.',
        focusedLearningBlock: 'Read Chapter 2, pages 19–34. Focus specifically on the moments where Parrish describes people who succeeded by NOT reacting immediately. Hold in mind: what does it physically feel like when you\'re about to default?',
        detailedBreakdown: '**The pause as a trainable skill**\nParrish argues that the ability to pause before reacting is not a personality trait — it\'s a muscle. Like any muscle, it atrophies without use and grows with deliberate practice.\n\n**Why we skip the pause**\nSpeed feels like competence. In social situations, a quick response signals confidence. In high-stakes moments, fast action feels like control. These signals actively work against pausing.\n\n**How to build pause strength**\nParrish recommends three practices: creating physical space (literally moving away from the trigger), pre-committing to a delay ("I\'ll respond in one hour"), and establishing a "pause phrase" you say internally to interrupt the default.\n\n**The misconception**\nPausing is not the same as being passive or indecisive. The strongest leaders pause the longest before acting — because they know the pause is where the quality of a decision is determined.\n\n**Apply This:** What is one recurring situation in your life where you consistently react before thinking? Design a specific pause ritual for that exact moment.',
        dailyReflection: 'Without looking back, what was the core idea of this lesson?\n\nWhat does it cost you — emotionally, relationally, professionally — when you skip the pause?',
        diffuseThinkingPrompt: 'If the space between stimulus and response were a physical place, what would it look like?',
        deliberatePracticeTask: 'Choose one high-frequency trigger in your day (a type of email, a specific conversation, a recurring frustration). For 48 hours, practice inserting a 10-second delay before responding to it every single time. You\'ll notice your responses become qualitatively different by the second day.',
      },
      {
        id: 'mod-3', number: 3, status: 'learning',
        title: 'Knowing What You Want',
        keyWisdom: 'Clarity about what you want is a prerequisite for getting it.',
        quickSummary: 'Most people optimize for what\'s visible — status, money, approval — while neglecting what actually produces a good life. Parrish argues that knowing what you truly want is harder than it sounds and requires deliberate introspection.',
        focusedLearningBlock: 'Read Chapter 4, pages 55–72. Pay attention to how Parrish distinguishes between first-order desires (what we think we want) and second-order desires (what we want to want). Hold in mind: what is something you\'ve been pursuing that might be a first-order desire?',
        detailedBreakdown: '**First vs. second-order desires**\nA first-order desire is what you want right now — a cookie, validation, a quick win. A second-order desire is what you want for your life — health, integrity, deep relationships. The two often conflict.\n\n**Why this is hard**\nSociety is very good at manufacturing first-order desires through advertising, social media, and status signaling. Most of our wants were installed by outside forces, not generated from within.\n\n**The clarity exercise**\nParrish recommends asking: "If no one would ever know the outcome, would I still want this?" This removes social and ego defaults from the equation, leaving only what you genuinely value.\n\n**The misconception**\nPeople assume they know what they want. Parrish shows that most people are pursuing proxies — things that represent what they want but are not the thing itself.\n\n**Apply This:** Name three things you\'re currently pursuing. For each, ask: is this the thing itself, or a proxy for something deeper?',
        dailyReflection: 'Without looking back, what was the core idea of this lesson?\n\nWhat is one thing you\'re working toward right now that, if you\'re honest, you\'re not sure you actually want?',
        diffuseThinkingPrompt: 'If you stripped away everything you do for external approval, what would a typical Tuesday look like?',
        deliberatePracticeTask: 'Write a "want audit." List 10 things you\'re currently pursuing — habits, goals, social commitments. Next to each, write whether it\'s a first-order desire, a second-order desire, or a proxy. Eliminate or pause one item that is clearly a proxy. You\'ll have a sharper sense of your real priorities by the end.',
      },
      {
        id: 'mod-4', number: 4, status: 'not_started',
        title: 'The Confidence–Competence Trap',
        keyWisdom: 'Feeling certain is not the same as being right.',
        quickSummary: 'Confidence is socially rewarded even when it\'s unearned. This creates a dangerous loop where the most confident voices dominate decisions, regardless of their actual competence. Parrish breaks down how to calibrate your confidence to your actual knowledge.',
        focusedLearningBlock: 'Read Chapter 6, pages 89–104. Note every example where confidence was mistaken for competence — in the book and in your own memory. Hold in mind: what is one area where you might be more confident than you are competent?',
        detailedBreakdown: '**The social reward for confidence**\nConfidence signals status and leadership potential. In group settings, the confident person is assumed to be the knowledgeable one — even without evidence. This dynamic selects for confidence over accuracy.\n\n**Calibration: what it is**\nA well-calibrated person is right in proportion to how confident they feel. When they\'re 90% confident, they\'re right about 90% of the time. Most people are systematically overconfident — especially in their areas of perceived expertise.\n\n**How to recalibrate**\nParrish recommends a practice called "consider the opposite": before committing to a position, seriously argue the strongest version of the opposing view. This destabilizes false certainty and surfaces blind spots.\n\n**The misconception**\nMost people think the goal is to be more confident. Parrish argues the goal is to be more accurate — which sometimes means being less confident.\n\n**Apply This:** Pick a belief you hold with high confidence. Write the strongest possible argument against it. Does your confidence level change?',
        dailyReflection: 'Without looking back, what was the core idea of this lesson?\n\nIn what domain of your life do you consistently project more confidence than your track record justifies?',
        diffuseThinkingPrompt: 'What would it look like if confidence and competence were always perfectly visible to others — like a color that changed based on your actual accuracy?',
        deliberatePracticeTask: 'Make 10 predictions about things that will happen this week — meetings, outcomes, conversations. Assign a confidence percentage to each. At the end of the week, check your accuracy. You\'ll find your calibration score and the specific areas where your confidence outruns your competence.',
      },
      {
        id: 'mod-5', number: 5, status: 'not_started',
        title: 'The Hierarchy of Thinking',
        keyWisdom: 'First-principles thinking beats pattern-matching when stakes are high.',
        quickSummary: 'We navigate most of life by pattern-matching — using past experiences to shortcut our way to decisions. This is efficient but brittle in novel situations. Parrish introduces the hierarchy of thinking: from rules of thumb at the bottom to first-principles reasoning at the top.',
        focusedLearningBlock: 'Read Chapter 8, pages 121–138. Identify two decisions in your own life where you relied on pattern-matching when first-principles thinking would have served better. Hold in mind: what distinguishes a situation that warrants deep reasoning from one where a heuristic is fine?',
        detailedBreakdown: '**Pattern-matching: the default mode**\nOur brains are pattern recognition machines. When we see a situation, we instantly map it to past experiences and apply the same response. This is fast, energy-efficient, and usually good enough.\n\n**Where it breaks down**\nPattern-matching fails in genuinely novel situations — new industries, unprecedented decisions, first-time experiences. The map from the past doesn\'t fit the new territory. Yet we apply it anyway.\n\n**First-principles reasoning**\nInstead of asking "what did I do last time?", first-principles thinking asks: "what is actually true here, from scratch?" It breaks a problem down to its fundamental components and rebuilds a solution from the ground up.\n\n**The cost**\nFirst-principles thinking is expensive. It requires time, discomfort, and intellectual honesty. Parrish is clear: use it selectively, for high-stakes decisions where the cost of a wrong answer is high.\n\n**Apply This:** Think of a major decision you\'re facing. Are you pattern-matching from past experience, or reasoning from first principles? Which does this situation deserve?',
        dailyReflection: 'Without looking back, what was the core idea of this lesson?\n\nWhat\'s a belief you hold about how the world works that you\'ve never actually examined from first principles?',
        diffuseThinkingPrompt: 'If you had to explain your most important current problem to a brilliant 10-year-old who knew nothing about your industry or past, what would you say?',
        deliberatePracticeTask: 'Take one decision you\'ve been putting off. Write out your current plan based on what you\'ve done before or what others typically do. Then write a second plan built purely from first principles — ignoring convention entirely. Compare the two. You\'ll notice at least one assumption in your original plan that doesn\'t actually hold up.',
      },
    ],
  },
}
